name: "Build Next.js Application"
description: "Build and archive Next.js application with production environment"
inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "22.x"
  sentry-auth-token:
    description: "Sentry auth token"
    required: false
    default: ""
  sentry-dsn:
    description: "Sentry DSN"
    required: false
    default: ""
  database-url:
    description: "Database URL"
    required: false
    default: ""
  app-url:
    description: "Application URL"
    required: false
    default: ""
  resend-api-key:
    description: "Resend API key"
    required: false
    default: ""
  resend-from-email:
    description: "Resend from email"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Build static website
      id: build
      shell: bash
      env:
        NODE_ENV: production
        SENTRY_AUTH_TOKEN: ${{ inputs.sentry-auth-token }}
        NEXT_PUBLIC_SENTRY_DSN: ${{ inputs.sentry-dsn }}
        DATABASE_URL: ${{ inputs.database-url }}
        NEXT_PUBLIC_APP_URL: ${{ inputs.app-url }}
        RESEND_API_KEY_PROD: ${{ inputs.resend-api-key }}
        RESEND_FROM_EMAIL_PROD: ${{ inputs.resend-from-email }}
      run: |
        echo "Starting build process..."
        npm run build
        echo "Build completed successfully"
        echo "build_success=true" >> $GITHUB_OUTPUT

    - name: Verify build output
      if: steps.build.outputs.build_success == 'true'
      shell: bash
      run: |
        echo "Verifying build output..."
        if [ -d ".next" ]; then
          echo "Build output directory exists"
          ls -la .next/
        else
          echo "Build output directory not found"
          exit 1
        fi

    - name: Archive Release
      if: steps.build.outputs.build_success == 'true'
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: "zip"
        filename: "release.zip"

    - name: Upload Release Artifact
      if: steps.build.outputs.build_success == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: release-archive
        path: release.zip

    - name: Build Failed - Upload Logs
      if: failure() && steps.build.conclusion == 'failure'
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          .next/
          *.log
          npm-debug.log*
          yarn-debug.log*
          yarn-error.log*
