/* eslint-disable @next/next/no-page-custom-font */
import NavBar from "@/components/shared/header/NavBar";
import "../styles/globals.scss";
import Footer from "@/components/shared/footer/Footer";
import Head from "next/head";
import ThemeProvider from "@/context/ThemeContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body>
          <NavBar />
          {children}
          <Footer />
        </body>
      </ThemeProvider>
    </html>
  );
}
