/* eslint-disable @next/next/no-page-custom-font */
import NavBar from "@/components/shared/header/NavBar";
import "../styles/globals.scss";
import Footer from "@/components/shared/footer/Footer";
import Head from "next/head";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
