name: Next.js Application - Build, Archive, and Release on Main Branch Push

on:
  push:
    branches:
      - main

jobs:
  build-and-archive:
    name: Build and Archive Next.js Application
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Run API tests
        env:
          NODE_ENV: test
          DATABASE_URL: ${{ secrets.DB_PROD_MONGODB_URI }}
        run: npm run test:api

      - name: Build static website
        env:
          NODE_ENV: production
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          DATABASE_URL: ${{ secrets.DB_PROD_MONGODB_URI }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
          RESEND_API_KEY_PROD: ${{ secrets.RESEND_API_KEY_PROD }}
          RESEND_FROM_EMAIL_PROD: ${{ secrets.RESEND_FROM_EMAIL_PROD }}
        run: npm run build

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          filename: "release.zip"

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-archive
          path: release.zip

  release:
    name: Release to GitHub
    runs-on: ubuntu-latest
    needs: build-and-archive

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Download Release Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-archive

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
