name: Next.js Application - Build, Archive, and Release on Main Branch

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '22.x'

jobs:
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'

    steps:
      - name: Run API tests
        uses: ./.github/actions/run-tests
        with:
          test-type: 'api'
          node-version: ${{ env.NODE_VERSION }}

  component-tests:
    name: Run Component Tests
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'

    steps:
      - name: Run Component tests
        uses: ./.github/actions/run-tests
        with:
          test-type: 'component'
          node-version: ${{ env.NODE_VERSION }}

  build-and-archive:
    name: Build and Archive Next.js Application
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.api-tests.result == 'success' && needs.component-tests.result == 'success'
    needs: [api-tests, component-tests]

    steps:
      - name: Build and Archive Application
        uses: ./.github/actions/build-app
        with:
          node-version: ${{ env.NODE_VERSION }}

  release:
    name: Release to GitHub
    runs-on: ubuntu-latest
    needs: [api-tests, component-tests, build-and-archive]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.build-and-archive.result == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Download Release Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-archive

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  notify-failure:
    name: Notify on Failure
    runs-on: ubuntu-latest
    needs: [api-tests, component-tests, build-and-archive, release]
    if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Notify Failure
        run: |
          echo "❌ Workflow failed for commit ${{ github.sha }}"
          echo "Failed jobs: ${{ toJson(needs) }}"
